// Scryfall Shape
interface Card {
  object: string,
  id: string,
  oracle_id: string,
  multiverse_ids: [],
  mtgo_id: string,
  mtgo_foil_id: string,
  tcgplayer_id: string,
  cardmarket_id: string,
  name: string,
  lang: string,
  released_at: string,
  uri: string,
  scryfall_uri: string,
  layout: string,
  highres_image: boolean,
  image_status: string,
  image_uris: {
    small: string,
    normal: string,
    large: string,
    png: string,
    art_crop: string,
    border_crip: string,
  },
  mana_cost: string,
  cmc: string,
  type_line: string,
  oracle_text: string,
  colors: [],
  color_identity: [],
  keywords: [],
  legalities: {
    standard: string,
    future: string,
    historic: string,
    timeless: string,
    gladiator: string,
    pioneer: string,
    explorer: string,
    modern: string,
    legacy: string,
    pauper: string,
    vintage: string,
    penny: string,
    commander: string,
    oathbreaker: string,
    standardbrawl: string,
    brawl: string,
    alchemy: string,
    paupercommander: string,
    duel: string,
    oldschool: string,
    premodern: string,
    predh: string,
  },
  games: [],
  reserved: boolean,
  foil: boolean,
  nonfoil: boolean,
  finishes: [],
  oversized: boolean,
  promo: boolean,
  reprint: boolean,
  variation: boolean,
  set_id: string,
  set: string,
  set_name: string,
  set_type: string,
  set_uri: string,
  set_search_uri: string,
  scryfall_set_uri: string,
  rulings_uri: string,
  prints_search_uri: string,
  collector_number: string,
  digital: boolean,
  rarity: string,
  flavor_text: string,
  card_back_id: string,
  artist: string,
  artist_ids: [],
  illustration_id: string,
  border_color: string,
  frame: string,
  full_art: boolean,
  textless: boolean,
  booster: boolean,
  story_spotlight: boolean,
  edhrec_rank: number,
  penny_rank: number,
  prices: {
    usd: string,
    usd_foil: string,
    usd_etched: string,
    eur: string,
    eur_foil: string,
    tix: string,
  },
  related_uris: {
    gatherer: string,
    tcgplayer_infinite_articles: string,
    tcgplayer_infinite_decks: string,
    edhrec: string,
  },
  purchase_uris: {
    tcgplayer: string,
    cardmarket: string,
    cardhoarder: string,
  }
}

interface CardProps {
  card: Card
}

interface GathererCardObj {
    name: string,
    manaCost: string,
    cmc: number,
    colors: Array<string>,
    colorIdentity: Array<string>,
    type: string,
    types: Array<string>,
    subtypes: Array<string>,
    rarity: string,
    set: string,
    setname: string,
    text: string,
    flavor: string,
    artist: string,
    number: string,
    power: string,
    toughness: string,
    layout: string,
    variations: Array<string>,
    printings: Array<string>,
    legalitites: Array<string>,
    id: string,
  }
  
  interface ScryfallCardObj {
    object: string,
    id: string,
    oracle_id: string,
    multiverse_ids: [],
    mtgo_id: string,
    mtgo_foil_id: string,
    tcgplayer_id: string,
    cardmarket_id: string,
    name: string,
    lang: string,
    released_at: string,
    uri: string,
    scryfall_uri: string,
    layout: string,
    highres_image: boolean,
    image_status: string,
    image_uris: {
      small: string,
      normal: string,
      large: string,
      png: string,
      art_crop: string,
      border_crip: string,
    },
    mana_cost: string,
    cmc: string,
    type_line: string,
    oracle_text: string,
    colors: [],
    color_identity: [],
    keywords: [],
    legalities: {
      standard: string,
      future: string,
      historic: string,
      timeless: string,
      gladiator: string,
      pioneer: string,
      explorer: string,
      modern: string,
      legacy: string,
      pauper: string,
      vintage: string,
      penny: string,
      commander: string,
      oathbreaker: string,
      standardbrawl: string,
      brawl: string,
      alchemy: string,
      paupercommander: string,
      duel: string,
      oldschool: string,
      premodern: string,
      predh: string,
    },
    games: [],
    reserved: boolean,
    foil: boolean,
    nonfoil: boolean,
    finishes: [],
    oversized: boolean,
    promo: boolean,
    reprint: boolean,
    variation: boolean,
    set_id: string,
    set: string,
    set_name: string,
    set_type: string,
    set_uri: string,
    set_search_uri: string,
    scryfall_set_uri: string,
    rulings_uri: string,
    prints_search_uri: string,
    collector_number: string,
    digital: boolean,
    rarity: string,
    flavor_text: string,
    card_back_id: string,
    artist: string,
    artist_ids: [],
    illustration_id: string,
    border_color: string,
    frame: string,
    full_art: boolean,
    textless: boolean,
    booster: boolean,
    story_spotlight: boolean,
    edhrec_rank: number,
    penny_rank: number,
    prices: {
      usd: string,
      usd_foil: string,
      usd_etched: string,
      eur: string,
      eur_foil: string,
      tix: string,
    },
    related_uris: {
      gatherer: string,
      tcgplayer_infinite_articles: string,
      tcgplayer_infinite_decks: string,
      edhrec: string,
    },
    purchase_uris: {
      tcgplayer: string,
      cardmarket: string,
      cardhoarder: string,
    }
  }

  interface ScryfallDoubleSidedCardObj {
    object: string,
    id: string,
    oracle_id: string,
    multiverse_ids: number[],
    mtgo_id: number,
    arena_id: number,
    tcgplayer_id: number,
    cardmarket_id: number,
    name: string,
    lang: string,
    released_at: string,
    uri: string,
    scryfall_uri: string,
    layout: string,
    highres_image: boolean,
    image_status: string,
    cmc: number,
    type_line: string,
    color_identity: string[],
    keywords: string[],
    card_faces: [
      {
        object: string,
        name: string,
        mana_cost: string,
        type_line: string,
        oracle_text: string,
        colors: string[],
        power: string,
        toughness: string,
        artist: string,
        artist_id: string,
        illustration_id: string,
        image_uris: {
          small: string,
          normal: string,
          large: string,
          png: string,
          art_crop: string,
          border_crop: string
        }
      },
      {
        object: string,
        name: string,
        mana_cost: string,
        type_line: string,
        oracle_text: string,
        colors: string[],
        power: string,
        toughness: string,
        artist: string,
        artist_id: string,
        illustration_id: string,
        image_uris: {
          small: string,
          normal: string,
          large: string,
          png: string,
          art_crop: string,
          border_crop: string
        }
      }
    ],
    all_parts: [
      {
        object: string,
        id: string,
        component: string,
        name: string,
        type_line: string,
        uri: string
      },
      {
        object: string,
        id: string,
        component: string,
        name: string,
        type_line: string,
        uri: string
      }
    ],
    legalities: {
      standard: string,
      future: string,
      historic: string,
      timeless: string,
      gladiator: string,
      pioneer: string,
      explorer: string,
      modern: string,
      legacy: string,
      pauper: string,
      vintage: string,
      penny: string,
      commander: string,
      oathbreaker: string,
      standardbrawl: string,
      brawl: string,
      alchemy: string,
      paupercommander: string,
      duel: string,
      oldschool: string,
      premodern: string,
      predh: string,
    },
    games: string[],
    reserved: boolean,
    foil: boolean,
    nonfoil: boolean,
    finishes: string[],
    oversized: boolean,
    promo: boolean,
    reprint: boolean,
    variation: boolean,
    set_id: string,
    set: string,
    set_name: string,
    set_type: string,
    set_uri: string,
    set_search_uri: string,
    scryfall_set_uri: string,
    rulings_uri: string,
    prints_search_uri: string,
    collector_number: number,
    digital: boolean,
    rarity: string,
    artist: string,
    artist_ids: string[],
    border_color: string,
    frame: string,
    security_stamp: string,
    full_art: boolean,
    textless: boolean,
    booster: boolean,
    story_spotlight: boolean,
    edhrec_rank: number,
    penny_rank: number,
    prices: {
      usd: string,
      usd_foil: string,
      usd_etched: string,
      eur: string,
      eur_foil: string,
      tix: string,
    },
    related_uris: {
      gatherer: string,
      tcgplayer_infinite_articles: string,
      tcgplayer_infinite_decks: string,
      edhrec: string,
    },
    purchase_uris: {
      tcgplayer: string,
      cardmarket: string,
      cardhoarder: string,
    }
  }